# Generated by Django 4.2.5 on 2023-10-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatleaders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatboardleaderssetup',
            name='output_channel_id',
        ),
    ]
