# Generated by Django 4.2.8 on 2024-01-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatleaders', '0002_remove_fatboardleaderssetup_output_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardtypethrough',
            name='header_line_two',
            field=models.CharField(blank=True, default='', help_text='Column header line two, show to the user.', max_length=250),
        ),
        migrations.AlterField(
            model_name='leaderboardtypethrough',
            name='header',
            field=models.CharField(help_text='Column header line one, show to the user.', max_length=250),
        ),
    ]
