# Generated by Django 4.2.8 on 2024-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0021_alter_afatlink_fleet'),
        ('fatleaders', '0003_leaderboardtypethrough_header_line_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatboardleaderssetup',
            name='types_in_ratio',
            field=models.ManyToManyField(blank=True, related_name='ratio_types', to='afat.afatlinktype'),
        ),
    ]
