# Generated by Django 4.2.8 on 2024-01-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0023_the_big_rename'),
        ('fatleaders', '0004_fatboardleaderssetup_types_in_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatboardleaderssetup',
            name='types_in_ratio',
            field=models.ManyToManyField(blank=True, related_name='ratio_types', to='afat.fleettype'),
        ),
        migrations.AlterField(
            model_name='fatboardleaderssetup',
            name='types_to_breakout',
            field=models.ManyToManyField(blank=True, through='fatleaders.LeaderBoardTypeThrough', to='afat.fleettype'),
        ),
        migrations.AlterField(
            model_name='leaderboardtypethrough',
            name='fatLinkType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afat.fleettype'),
        ),
    ]
